language: cpp
os: linux
dist: trusty 
sudo: false
compiler: gcc
branches:
  only:
    - master
addons:
  apt:
    packages:
    - graphviz
    - doxygen

before_script:
  - make clean

script:
  - make
  - make test
  - make docs

after_success:
  - make publish
