language: cpp
os: linux
dist: trusty 
sudo: false
compiler: gcc
addons:
  apt:
    packages:
    - libglew-dev
    - graphviz
    - doxygen

before_script:
  - make clean

script:
  - make
  - make test
